package aplicacion.modelo.dominio;
// Generated 10-jun-2019 2:25:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
/**
 * Categorias generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int idcategoria;
     private String nombre;
     private String descripcion;
     private Set productoses = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int idcategoria) {
        this.idcategoria = idcategoria;
    }
    public Categoria(int idcategoria, String nombre, String descripcion, Set productoses) {
       this.idcategoria = idcategoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.productoses = productoses;
    }
   
    public int getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(int idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }

    @Override
    public String toString() {
        return String.format("Categoria: [%S,%S]",descripcion, nombre);
    }

    

    
    /*@Override
    public int hashCode(){
        int hash = 7;
        hash = 47 * hash + this.getIdcategoria();
        hash = 47 * hash + Objects.hashCode(this.getNombre());
        hash = 47 * hash + Objects.hashCode(this.getDescripcion());
        hash = 47 * hash + Objects.hashCode(this.getProductoses());
        return hash;
    }
    
    @Override
    public boolean equals(Object obj){
        if(this == obj){
           return true;
        }
        if(obj == null){
           return false;
        }
        if(getClass() != obj.getClass()){
           return false;
        }
        final Categoria other = (Categoria) obj;
        if (this.getIdcategoria() != other.getIdcategoria()){
           return false;
        }
        return true;
    }*/

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 47 * hash + this.idcategoria;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Categoria other = (Categoria) obj;
        if (this.idcategoria != other.idcategoria) {
            return false;
        }
        return true;
    }  
 }
